export const requestStatus = {
  IDLE: 'IDLE',
  PENDING: 'PENDING',
  FULFILLED: 'FULFILLED',
  REJECTED: 'REJECTED',
  ABORTED: 'ABORTED',
  FORCE_IDLE: 'IDLE',
  FORCE_PENDING: 'PENDING',
  FORCE_FULFILLED: 'FULFILLED',
  FORCE_REJECTED: 'REJECTED',
  FORCE_ABORTED: 'ABORTED',
} as const;
